### ISSUE TITLE
FPM Socket Permission denied

### ISSUE THREAD

**Issue by ghost** [javer/hhvm-vagrant-vm#18]
Hey,

I checked this out and built everything. The hhvm works, but the fpm gives me a permission denied when connecting to the socket:

[crit] 26634#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 10.0.2.2, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "127.0.0.1:9080"

ls -l /var/run
srw-rw---- 1 root       root          0 Jul  6 15:47 php-fpm.sock (no read access)

Is there anything, we can do?

**Comment by javer** [comment]
@csiewert, thanks for letting me know!

You can fix your VM without rebuild by patching file /etc/php5/fpm/pool.d/site.conf as in commit 998be4258c3e569439ae3f757f4a03c8405a3465.

**Comment by ghost** [comment]
Thanks @javer
