### ISSUE TITLE
c++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by staabm** [javer/hhvm-vagrant-vm#8]
got another error from cmake

```
[ 69%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/ji
t/region-hot-block.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/vm/jit/hhbc-transl
ator.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2
make: *** [all] Error 2
```

again the question... is this error related to e.g. the custom gcc for the vm? or is it a temporary hhvm dev version error?

**Comment by javer** [comment]
I've seen this error many times, every time it appears on another file and line. It is fixed by restarting make after login to the VM. When I used only 2 cores this error appears very rare, but compiling takes 2x time.

Another thing is to use gcc 4.8.2, someone wrote that it will fix this issue.

**Comment by staabm** [comment]
I will try to use gcc 4.8.2..

Anything more we could do to reduce compile time? Maybe some parallelism?

**Comment by javer** [comment]
I think there is no need to think about ways to speed up compilation as it is performed only once in a few days. Also instead of rebuilding VM from scratch we can login into existing VM, update HHVM sources from git and run cmake and make.

**Comment by shivaas** [comment]
upgrading to gcc4.8 and stepping down to -j4 on Ubuntu 12.04 LTS solved this issue for me

**Comment by javer** [comment]
Thanks @shivaas
