### ISSUE TITLE
HHVM doesn't compile

### ISSUE THREAD

**Issue by justinhj** [javer/hhvm-vagrant-vm#9]
HHVM fails to compile

I am at commit d5dcd18

Everything went smoothly after vagrant up except that hhvm was not running. When I followed the instructions in the readme to compile it, it tried build but failed 53% in as follows:

[ 53%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/ext/gd/libgd/xbm.cpp.o
/root/dev/hhvm/hphp/runtime/ext/gd/libgd/gdft.cpp:64:38: fatal error: freetype/config/ftheader.h: No such file or directory
compilation terminated.
[ 53%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/ext/gd/libgd/gd_gif_in.cpp.o
[ 53%] Building CXX object hphp/runtime/CMakeFiles/hphp_runtime_static.dir/ext/gd/libgd/gdkanji.cpp.o
make[2]: **\* [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/ext/gd/libgd/gdft.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[1]: **\* [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2
make: **\* [all] Error 2

**Comment by javer** [comment]
Thanks for reporting this! Fixed in https://github.com/facebook/hhvm/commit/c3bd6fa66afba218ac21a3312b2b9d9bf7fdc9ef
